<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Staybook.ServiceDefaults\Staybook.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Modules\Identity\Staybook.Identity\Staybook.Identity.csproj" />
    <ProjectReference Include="..\Modules\Listings\Staybook.Listings\Staybook.Listings.csproj" />
    <ProjectReference Include="..\Modules\Pricing\Staybook.Pricing\Staybook.Pricing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
    <PackageReference Include="Marten" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

</Project>
